### ISSUE TITLE
File "python/resnet_generator.py", line 21, in add_conv_layer     conv_layer.bottom._values.append(bottom) AttributeError: 'google.protobuf.pyext._message.RepeatedScalarConta' object has no attribute '_values'

### ISSUE THREAD

**Issue by chowkamlee81** [wenwei202/caffe#28]
When trying to execute 
 python python/resnet_generator.py --net_template examples/cifar10/resne
t_template.prototxt --n 3 --force_regularization

got the error below:

Traceback (most recent call last):
  File "python/resnet_generator.py", line 281, in <module>
    add_conv_layer(net_msg,name='conv1',bottom='data',num_output=16,pad=1,kernel_size=3,stride=1,connectivity_mode=connectivity_mode)
  File "python/resnet_generator.py", line 21, in add_conv_layer
    conv_layer.bottom._values.append(bottom)
AttributeError: 'google.protobuf.pyext._message.RepeatedScalarConta' object has no attribute '_values'

Kindly suggest how to  go ahead

**Comment by wenwei202** [comment]
Seems the protobuf goes wrong. You may check if you have multiple versions of protobuf installed and try to remove one.

**Comment by HKLee2040** [comment]
I met the same problem.   May I know which version do you use?

**Comment by wenwei202** [comment]
@HKLee2040 I am not sure. May be 2.4. Please check if you have multiple protobuf versions installed and uninstall some.
